### ISSUE TITLE
Error waiting for no transient callbacks from Flutter driver: `Failed assertion: boolean expression must not be null`

### ISSUE THREAD

**Issue by comerc** [jerseysu/flutter_bdd#1]
```
Using device Android SDK built for x86.
Starting application: test_driver/app.dart
Installing build/app/outputs/flutter-apk/app.apk...                 4,3s
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY .
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        18,7s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
I/flutter ( 5883): Observatory listening on http://127.0.0.1:42852/XnwWdV-4asg=/
Starting Flutter app under test 'test_driver/app.dart', this might take a few moments
I/flutter ( 5954): Observatory listening on http://127.0.0.1:50758/5FACdXdbDug=/
before run hook
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:38029/5FACdXdbDug=/
VMServiceFlutterDriver: Isolate found with number: 3671038823464699
VMServiceFlutterDriver: Isolate is not paused. Assuming application is ready.
VMServiceFlutterDriver: Connected to Flutter application.
running hook before scenario 'Check App Title And Content'
Running scenario: Check App Title And Content # ./test_driver/features/hello_world.feature:3
   √ Given I expect the "firstTabTitle" to be "Jeresy Cool!" # ./test_driver/features/hello_world.feature:4 took 129ms
   √ Then I expect the "textField" to be "Hello, Jersey!" # ./test_driver/features/hello_world.feature:5 took 54ms
PASSED: Scenario Check App Title And Content # ./test_driver/features/hello_world.feature:3
Restarting Flutter app under test
running hook after scenario 'Check App Title And Content'
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:38029/5FACdXdbDug=/
Error waiting for no transient callbacks from Flutter driver:

`Failed assertion: boolean expression must not be null`

#0      VMServiceFlutterDriver.sendCommand (package:flutter_driver/src/driver/vmservice_driver.dart:351:29)
<asynchronous suspension>
#1      FlutterDriver.waitUntilNoTransientCallbacks (package:flutter_driver/src/driver/driver.dart:230:11)
#2      FlutterWorld._closeDriver (package:flutter_gherkin/src/flutter/flutter_world.dart:49:14)
#3      FlutterWorld.dispose (package:flutter_gherkin/src/flutter/flutter_world.dart:40:11)
#4      FeatureFileRunner._runScenario (package:gherkin/src/feature_file_runner.dart:276:16)
<asynchronous suspension>
#5      FeatureFileRunner._runScenarioInZone.<anonymous closure> (package:gherkin/src/feature_file_runner.dart:142:30)
#6      _rootRun (dart:async/zone.dart:1190:13)
#7      _CustomZone.run (dart:async/zone.dart:1093:19)
#8      _runZoned (dart:async/zone.dart:1630:10)
#9      runZonedGuarded (dart:async/zone.dart:1618:12)
#10     runZoned (dart:async/zone.dart:1547:12)
#11     FeatureFileRunner._runScenarioInZone (package:gherkin/src/feature_file_runner.dart:140:5)
#12     FeatureFileRunner._runFeature (package:gherkin/src/feature_file_runner.dart:74:21)
<asynchronous suspension>
#13     FeatureFileRunner.run (package:gherkin/src/feature_file_runner.dart:41:38)
#14     GherkinRunner.execute (package:gherkin/src/test_runner.dart:86:45)
<asynchronous suspension>
#15     main (file:///home/aka/try-flutter/flutter_bdd/test_driver/app_test.dart:32:26)
#16     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

VMServiceFlutterDriver: Isolate found with number: 1298931021565975
VMServiceFlutterDriver: Isolate is not paused. Assuming application is ready.
VMServiceFlutterDriver: Connected to Flutter application.
running hook before scenario 'Check App Title When Switch Page'
Running scenario: Check App Title When Switch Page # ./test_driver/features/hello_world.feature:7
Instance of 'VMServiceFlutterDriver'
   √ Given I go to second page # ./test_driver/features/hello_world.feature:8 took 611ms
Instance of 'VMServiceFlutterDriver'
   √ Then I expect second page title to be "Jersey Second Tab" # ./test_driver/features/hello_world.feature:9 took 201ms
Instance of 'VMServiceFlutterDriver'
   √ When I go to landing page # ./test_driver/features/hello_world.feature:10 took 453ms
Instance of 'VMServiceFlutterDriver'
   √ Then I expect landing page title to be "Jeresy Cool!" # ./test_driver/features/hello_world.feature:11 took 88ms
PASSED: Scenario Check App Title When Switch Page # ./test_driver/features/hello_world.feature:7
Restarting Flutter app under test
running hook after scenario 'Check App Title When Switch Page'
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:38029/5FACdXdbDug=/
Error waiting for no transient callbacks from Flutter driver:

`Failed assertion: boolean expression must not be null`

#0      VMServiceFlutterDriver.sendCommand (package:flutter_driver/src/driver/vmservice_driver.dart:351:29)
<asynchronous suspension>
#1      FlutterDriver.waitUntilNoTransientCallbacks (package:flutter_driver/src/driver/driver.dart:230:11)
#2      FlutterWorld._closeDriver (package:flutter_gherkin/src/flutter/flutter_world.dart:49:14)
#3      FlutterWorld.dispose (package:flutter_gherkin/src/flutter/flutter_world.dart:40:11)
#4      FeatureFileRunner._runScenario (package:gherkin/src/feature_file_runner.dart:276:16)
<asynchronous suspension>
#5      FeatureFileRunner._runScenarioInZone.<anonymous closure> (package:gherkin/src/feature_file_runner.dart:142:30)
#6      _rootRun (dart:async/zone.dart:1190:13)
#7      _CustomZone.run (dart:async/zone.dart:1093:19)
#8      _runZoned (dart:async/zone.dart:1630:10)
#9      runZonedGuarded (dart:async/zone.dart:1618:12)
#10     runZoned (dart:async/zone.dart:1547:12)
#11     FeatureFileRunner._runScenarioInZone (package:gherkin/src/feature_file_runner.dart:140:5)
#12     FeatureFileRunner._runFeature (package:gherkin/src/feature_file_runner.dart:74:21)
<asynchronous suspension>
#13     FeatureFileRunner.run (package:gherkin/src/feature_file_runner.dart:41:38)
#14     GherkinRunner.execute (package:gherkin/src/test_runner.dart:86:45)
<asynchronous suspension>
#15     main (file:///home/aka/try-flutter/flutter_bdd/test_driver/app_test.dart:32:26)
#16     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

VMServiceFlutterDriver: Isolate found with number: 248221512356987
VMServiceFlutterDriver: Isolate is not paused. Assuming application is ready.
VMServiceFlutterDriver: Connected to Flutter application.
running hook before scenario 'Check Counter Number'
Running scenario: Check Counter Number # ./test_driver/features/counter.feature:3
   √ Given I expect the "counterTextField" to be "0" # ./test_driver/features/counter.feature:4 took 234ms
Instance of 'VMServiceFlutterDriver'
   √ When I tap the "addBtn" button 20 times # ./test_driver/features/counter.feature:5 took 5140ms
   √ Then I expect the "counterTextField" to be "20" # ./test_driver/features/counter.feature:6 took 62ms
PASSED: Scenario Check Counter Number # ./test_driver/features/counter.feature:3
Restarting Flutter app under test
running hook after scenario 'Check Counter Number'
3 scenarios (3 passed)
9 steps (9 passed)
0:00:21.211000
Terminating Flutter app under test
Error waiting for no transient callbacks from Flutter driver:

`Failed assertion: boolean expression must not be null`

#0      VMServiceFlutterDriver.sendCommand (package:flutter_driver/src/driver/vmservice_driver.dart:351:29)
<asynchronous suspension>
#1      FlutterDriver.waitUntilNoTransientCallbacks (package:flutter_driver/src/driver/driver.dart:230:11)
#2      FlutterWorld._closeDriver (package:flutter_gherkin/src/flutter/flutter_world.dart:49:14)
#3      FlutterWorld.dispose (package:flutter_gherkin/src/flutter/flutter_world.dart:40:11)
#4      FeatureFileRunner._runScenario (package:gherkin/src/feature_file_runner.dart:276:16)
<asynchronous suspension>
#5      FeatureFileRunner._runScenarioInZone.<anonymous closure> (package:gherkin/src/feature_file_runner.dart:142:30)
#6      _rootRun (dart:async/zone.dart:1190:13)
#7      _CustomZone.run (dart:async/zone.dart:1093:19)
#8      _runZoned (dart:async/zone.dart:1630:10)
#9      runZonedGuarded (dart:async/zone.dart:1618:12)
#10     runZoned (dart:async/zone.dart:1547:12)
#11     FeatureFileRunner._runScenarioInZone (package:gherkin/src/feature_file_runner.dart:140:5)
#12     FeatureFileRunner._runFeature (package:gherkin/src/feature_file_runner.dart:74:21)
<asynchronous suspension>
#13     FeatureFileRunner.run (package:gherkin/src/feature_file_runner.dart:41:38)
#14     GherkinRunner.execute (package:gherkin/src/test_runner.dart:86:45)
<asynchronous suspension>
#15     main (file:///home/aka/try-flutter/flutter_bdd/test_driver/app_test.dart:32:26)
#16     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

after run hook
Stopping application instance.
```

**Comment by comerc** [comment]
```
$ flutter doctor -v
Waiting for another flutter command to release the startup lock...
[✓] Flutter (Channel stable, 1.22.2, on Linux, locale ru_RU.UTF-8)
    • Flutter version 1.22.2 at /home/aka/flutter
    • Framework revision 84f3d28555 (3 недели назад), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/aka/Android/Sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.9+11-Ubuntu-0ubuntu1.18.04.1)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)

! Doctor found issues in 2 categories.
```

**Comment by jerseysu** [comment]
@comerc 
Thanks for reporting the issue, and thanks for keeps supporting this project, looking into the error message you provided,
`$ flutter doctor -v` shows the suspicious error as follow, could you recheck your environment and make sure the Android Studio and license is installed properly? thanks!!

```
[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
```

**Comment by jerseysu** [comment]
Hi @comerc 
I've upgrade the flutter to 2.0.1 version and do fix the issue, please pull down the master branch and rerun again to see if the issue mitigated, thanks!
